apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: todo-api
  annotations:
    run.googleapis.com/cloudsql-instances: velvety-matter-471516-n4:us-central1:todo-postgres
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/velvety-matter-471516-n4/todo-api:latest
        ports:
        - containerPort: 8080
          name: http1
        env:
        - name: RUST_LOG
          value: info
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: latest
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: latest
        - name: HASHING_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: hashing-secret
              key: latest
        - name: FRONTEND_URL
          valueFrom:
            secretKeyRef:
              name: frontend-url
              key: latest
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.5"
            memory: 256Mi